config/routes.rb
Rails.application.routes.draw do
  get "user2s/index"
  get "user2s/edit"
  get "user2s/new"
  get "user2s/show"
  get "employee1s/index"
  get "employee1s/edit"
  get "employee1s/new"
  get "employee1s/show"
  devise_for :user1s
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # for Products
  resources :products
  # root 'products#index'

  # for Authors
  resources :authors
  # root 'authors#index'

  #for Books
  resources :books

  #for Faculties
  resources :faculties
  # root "faculties#index"

  #for Students
  resources :students

  # JavaScript with rails
  resources :js_users do
    member do
      get :profile
      patch :profile_update
      get :changepassword
      patch :changepassword_update
    end
  end

  root "js_users#index"

  #for Employees
  # root "employees#index"
  post "/increaseOrder", to: "employees#increaseOrder"
  post "/decreaseOrder", to: "employees#decreaseOrder"
  get "employees/task"
  resources :employees

  # root "myproducts#index"
  get "myproducts/defaultScope"
  get "orders/root"
  resources :myproducts
  resources :customers
  resources :orders

  # Active Record Association
  # root "events#index"
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: "log_in"
  delete "logout", to: "sessions#destroy"

  resources :users do
    collection do
      get :userprofile
    end
    member do
      get :enroll_event
      post :post_user
      get :unenroll_event
    end
  end

  resources :categories

  # Event Routes
  get "/:event_id/comments/new", to: "comments#new", :as => :new_comment
  post "/:event_id/comments/new", to: "comments#create"
  get "/events/:event_id/comments/:comment_id/edit", to: "comments#edit", :as => :edit_comment
  post "/events/:event_id/comments/:comment_id/edit/", to: "comments#update"
  delete "/events/:event_id/comments/:comment_id/", to: "comments#destroy", :as => :destroy_comment

  resources :events do
    resources :comments do
      member do
        post :like
      end
    end
  end

  # Resourceful Routes for rproducts
  resources :rproducts do
    resources :rorders
  end

  # Namespace Routing
  namespace :business do
    get "search", to: "rcustomers#search_customer"
    resources :rcustomers, only: [:index, :new, :create, :edit, :update] do
      member do
        get "name_preview"
        delete "delete_customer"
      end
    end
  end

  # root "rproducts#index"

  # Layouts Rendering Practical
  resources :user1s
  resources :product1s do
    resources :order1s
  end

  # root "home1s#index"

  # Action View form helpers
  get "search", to: "employee1s#search"
  resources :employee1s

  # root "employee1s#index"

  # Action mailer and basic file upload
  resources :user2s
  #root "user2s#index"

  # Test Cases Practical
  resources :product2s
  # root "home1s#index"

end

app/models/my_product.rb
class Myproduct < ApplicationRecord
  enum :status, {"In Stock":1, "Out Of Stock":2, ComingSoon:0}
  default_scope {where('is_active =?',true)}
  has_many :orders
end

app/models/myproduct.rb
class Myproduct < ApplicationRecord
  enum :status, {"In Stock":1, "Out Of Stock":2, ComingSoon:0}
  default_scope {where('is_active =?',true)}
  has_many :orders
end

app/controllers/myproducts_controller.rb
class MyproductsController < ApplicationController
  def index
    @myproducts = Myproduct.unscoped
  end

  def new
    @myproduct = Myproduct.new
  end

  def create
    @myproduct = Myproduct.create(myproduct_params)
    if @myproduct.valid?
      flash[:errors] = "Product Created Successfully"
      redirect_to myproducts_path
    else
      flash[:errors] = @myproduct.errors.full_messages
      redirect_to new_myproduct_path
    end
  end

  def show
    @myproduct = Myproduct.find(params[:id])
  end

  def edit
    @myproduct = Myproduct.find(params[:id])
  end

  def update
    @myproduct = Myproduct.find(params[:id])
    if @myproduct.update(myproduct_params)
      flash[:errors] = "Product Updated Successfully"
      redirect_to myproduct_path(@myproduct)
    else
      flash[:errors] = @myproduct.errors.full_messages
      redirect_to edit_myproduct_path
    end
  end

  def destroy
    @myproduct = Myproduct.find(params[:id])
    if @myproduct.delete
      flash[:errors] = "Product Deleted Successfully"
      redirect_to root_path(@myproduct)
    else
      flash[:errors] = @myproduct.errors.full_messages
      redirect_to destroy_myproduct_path
    end
  end

  def defaultScope
    @myproductscope = Myproduct.all
  end

  private
  def myproduct_params
    params.require(:myproduct).permit(:title, :description, :price, :capacity, :is_active, :status)
  end
end

app/helpers/myproducts_helper.rb
module MyproductsHelper
end

app/views/myproducts/defaultScope.html.erb
<%= render 'layouts/navbar'%>
<div class="center flex-column" style = "height: auto;">
  <h1> Default Scope </h1>

<!-- Product Table -->
  <div>
    <table class="table table-info table-striped">
      <ol class="fs-2">
        <thead class="table-secondary">
          <td class="text-center"> Title </td>
          <td class="text-center"> Description </td>
          <td class="text-center"> Price </td>
          <td class="text-center"> Capacity </td>
          <td class="text-center"> is_active </td>
          <td class="text-center"> Status </td>
          <td colspan=3 class="text-center"> Action </td>
        </thead>

        <% @myproductscope.each do |myproduct| %>
          <tr>
            <td class="text-center"> <%= link_to myproduct.title, myproduct_path(myproduct) %> </td>
            <td class="text-center"> <%= myproduct.description %> </td>
            <td class="text-center"> <%= myproduct.price %> </td>
            <td class="text-center"> <%= myproduct.capacity %> </td>
            <td class="text-center"> <%= myproduct.is_active %> </td>
            <td class="text-center"> <%= myproduct.status %> </td>
            
            <td class="text-center"><%= button_to "Show",myproduct_path(myproduct),method: :get, class:"btn-success border-0 rounded-pill shadow px-3 py-2" %></td>
            <td class="text-center"><%= button_to "Edit",edit_myproduct_path(myproduct),method: :get, class:"btn-primary border-0 rounded-pill shadow px-3 py-2" %></td>
            <td class="text-center"><%= button_to "Delete",myproduct_path(myproduct),method: :delete, class:"btn-danger border-0 rounded-pill shadow px-3 py-2" %></td>
          </tr>
        <% end %>
      </ol>
    </table>
  </div>

  <div class="d-flex">
    <%= button_to fa_icon("cube", text: "Product"), myproducts_path, method: :get ,class:"btn-warning border-0 rounded-pill shadow p-3 m-3" %>
    <%= button_to fa_icon("handshake-o", text: "Customer Page"), customers_path, method: :get ,class:"btn-success border-0 rounded-pill shadow p-3 m-3" %>
    <%= button_to fa_icon("shopping-cart", text: "Order Page"), orders_path, method: :get ,class:"btn-info border-0 rounded-pill shadow p-3 m-3" %>
  </div>
</div>

app/views/myproducts/edit.html.erb
<!-- File For Edit Student -->
<%= render 'layouts/navbar' %>
<div class="center flex-column">

<!-- Error Message -->
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <p class="text-danger"><%= error %></p>
    <% end %>
  <% end %>

  <!-- Edit Form Start Here -->
  <h1> Edit Product's Detail </h1>
  <%= form_for @myproduct, url: {action: :update} do |f| %>
    <%= f.label :title, "Title :", class:"mt-3" %>
    <%= f.text_field :title ,placeholder: "Enter Product's Title",class:"mb-2 form-control" %>
    <br>

    <%= f.label :description, "Description :" %>
    <%= f.text_field :description ,placeholder: "Enter Product's Description",class:"mb-2 form-control" %>
    <br>

    <%= f.label :price, "Price :" %>
    <%= f.number_field :price ,placeholder: "Enter Product's Price",class:"mb-2 form-control" %>
    <br>

    <%= f.label :capacity, "Capacity :" %>
    <%= f.number_field :capacity ,placeholder: "Enter Product's Capacity",class:"mb-2 form-control" %>
    <br>

    <%= f.label :is_active, "Is Product active?" %> &nbsp;
    <%= f.check_box :is_active,class:"form-check-input" %>
    <br> <br>

    <%= f.label :status, "Status :" %>
    <%= f.select(:status, Myproduct.statuses.keys) %>
    <br>
    
    <%= f.submit class:"btn-primary border-0 rounded-pill shadow p-3" %>
    
  <% end %>
</div>

app/views/myproducts/index.html.erb
<%= render 'layouts/navbar' %>
<div class="center flex-column" style = "height: auto;">
  <h1> MyProducts </h1>

  <!--Error Message-->
  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>

  <!-- Product Table -->
  <div>
    <table class="table table-info table-striped">
      <ol class="fs-2">
        <thead class="table-secondary">
          <td class="text-center"> Title </td>
          <td class="text-center"> Description </td>
          <td class="text-center"> Price </td>
          <td class="text-center"> Capacity </td>
          <td class="text-center"> is_active </td>
          <td class="text-center"> Status </td>
          <td colspan=3 class="text-center"> Action </td>
        </thead>

        <% @myproducts.each do |myproduct| %>
          <tr>
            <td class="text-center"> <%= link_to myproduct.title, myproduct_path(myproduct) %> </td>
            <td class="text-center"> <%= myproduct.description %> </td>
            <td class="text-center"> <%= myproduct.price %> </td>
            <td class="text-center"> <%= myproduct.capacity %> </td>
            <td class="text-center"> <%= myproduct.is_active %> </td>
            <td class="text-center"> <%= myproduct.status %> </td>      
            
            <td class="text-center"><%= button_to "Show",myproduct_path(myproduct),method: :get, class:"btn-success border-0 rounded-pill shadow px-3 py-2" %></td>
            <td class="text-center"><%= button_to "Edit",edit_myproduct_path(myproduct),method: :get, class:"btn-primary border-0 rounded-pill shadow px-3 py-2" %></td>
            <td class="text-center"><%= button_to "Delete",myproduct_path(myproduct),method: :delete, class:"btn-danger border-0 rounded-pill shadow px-3 py-2" %></td>
          </tr>
        <% end %>
      </ol>
    </table>
  </div>

  <div class="d-flex">
    <%= button_to fa_icon("plus", text: "Add New Product"), new_myproduct_path, method: :get ,class:"btn-warning border-0 rounded-pill shadow p-3 m-3" %>
    <%= button_to fa_icon("tasks", text: "Default Scope"), myproducts_defaultScope_path, method: :get ,class:"btn-info border-0 rounded-pill shadow p-3 m-3" %>
    <%= button_to fa_icon("handshake-o", text: "Customer Page"), customers_path, method: :get ,class:"btn-warning border-0 rounded-pill shadow p-3 m-3" %>
    <%= button_to fa_icon("shopping-cart", text: "Order Page"), orders_path, method: :get ,class:"btn-info border-0 rounded-pill shadow p-3 m-3" %>
  </div>

</div>

app/views/myproducts/new.html.erb
<%= render 'layouts/navbar' %>
<!-- Add New Product -->
<div class="center flex-column">
  <h1>Add New Product</h1>
  
  <!--Error Message-->
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <p class="text-danger"><%= error %></p>
    <% end %>
  <% end %>

  <%# Form Started Here %>
  <%= form_for @myproduct do |f| %>
    <%= f.label :title, "Title :", class:"mt-3" %>
    <%= f.text_field :title ,placeholder: "Enter Product's Title",class:"mb-2 form-control" %>
    <br>

    <%= f.label :description, "Description :" %>
    <%= f.text_field :description ,placeholder: "Enter Product's Description",class:"mb-2 form-control" %>
    <br>

    <%= f.label :price, "Price :" %>
    <%= f.number_field :price ,placeholder: "Enter Product's Price",class:"mb-2 form-control" %>
    <br>

    <%= f.label :capacity, "Capacity :" %>
    <%= f.number_field :capacity ,placeholder: "Enter Product's Capacity",class:"mb-2 form-control" %>
    <br>

    <%= f.label :is_active, "Is Product active?" %> &nbsp;
    <%= f.check_box :is_active,class:"form-check-input" %>
    <br> <br>

    <%= f.label :status, "Status :" %>
    <%= f.select(:status, Myproduct.statuses.keys) %>
    <br>

    <%= f.submit class:"btn-primary border-0 rounded-pill shadow p-3" %>
    
  <% end %>
</div>

app/views/myproducts/show.html.erb
<%= render 'layouts/navbar' %>
<!-- Product Details Showing -->
<div class="center flex-column">
  <h1>Product Details</h1>

  <!--Error Message-->
  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>

  <div>
    <h2> &#10145; Title: <%= @myproduct.title %> </h2>
    <h2> &#10145; Description: <%= @myproduct.description %> </h2>
    <h2> &#10145; Price: <%= @myproduct.price %> </h2>
    <h2> &#10145; Capacity: <%= @myproduct.capacity %> </h2>
    <h2> &#10145; Is_active: <%= @myproduct.is_active %></h2>
    <h2> &#10145; Status: <%= @myproduct.status %> </h2>
    <h2> &#10145; Order: <%= @myproduct.orders.count %> </h2>
  </div>

  <div class="d-flex">
    <%= button_to "Edit product" , edit_myproduct_path, method: :get ,class:"btn-success border-0 rounded-pill shadow p-2 m-2" %>
    <%= button_to "Delete product", myproduct_path, method: :delete ,class:"btn-danger border-0 rounded-pill shadow p-2 m-2" %>
    <%= button_to "View all Products", myproducts_path,method: :get ,class:"btn-primary border-0 rounded-pill shadow p-2 m-2" %>
  </div>
  
</div>