config/routes.rb
Rails.application.routes.draw do
  get "user2s/index"
  get "user2s/edit"
  get "user2s/new"
  get "user2s/show"
  get "employee1s/index"
  get "employee1s/edit"
  get "employee1s/new"
  get "employee1s/show"
  devise_for :user1s
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # for Products
  resources :products
  # root 'products#index'

  # for Authors
  resources :authors
  # root 'authors#index'

  #for Books
  resources :books

  #for Faculties
  resources :faculties
  # root "faculties#index"

  #for Students
  resources :students

  # JavaScript with rails
  resources :js_users do
    member do
      get :profile
      patch :profile_update
      get :changepassword
      patch :changepassword_update
    end
  end

  root "js_users#index"

  #for Employees
  # root "employees#index"
  post "/increaseOrder", to: "employees#increaseOrder"
  post "/decreaseOrder", to: "employees#decreaseOrder"
  get "employees/task"
  resources :employees

  # root "myproducts#index"
  get "myproducts/defaultScope"
  get "orders/root"
  resources :myproducts
  resources :customers
  resources :orders

  # Active Record Association
  # root "events#index"
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: "log_in"
  delete "logout", to: "sessions#destroy"

  resources :users do
    collection do
      get :userprofile
    end
    member do
      get :enroll_event
      post :post_user
      get :unenroll_event
    end
  end

  resources :categories

  # Event Routes
  get "/:event_id/comments/new", to: "comments#new", :as => :new_comment
  post "/:event_id/comments/new", to: "comments#create"
  get "/events/:event_id/comments/:comment_id/edit", to: "comments#edit", :as => :edit_comment
  post "/events/:event_id/comments/:comment_id/edit/", to: "comments#update"
  delete "/events/:event_id/comments/:comment_id/", to: "comments#destroy", :as => :destroy_comment

  resources :events do
    resources :comments do
      member do
        post :like
      end
    end
  end

  # Resourceful Routes for rproducts
  resources :rproducts do
    resources :rorders
  end

  # Namespace Routing
  namespace :business do
    get "search", to: "rcustomers#search_customer"
    resources :rcustomers, only: [:index, :new, :create, :edit, :update] do
      member do
        get "name_preview"
        delete "delete_customer"
      end
    end
  end

  # root "rproducts#index"

  # Layouts Rendering Practical
  resources :user1s
  resources :product1s do
    resources :order1s
  end

  # root "home1s#index"

  # Action View form helpers
  get "search", to: "employee1s#search"
  resources :employee1s

  # root "employee1s#index"

  # Action mailer and basic file upload
  resources :user2s
  #root "user2s#index"

  # Test Cases Practical
  resources :product2s
  # root "home1s#index"

end

app/models/js_user.rb
class JsUser < ApplicationRecord
  validates :first_name, :last_name, :email, presence: true
  validates :password, presence: true, on: :create
  validate :pwauthenticate, on: :update

  def pwauthenticate
    user = JsUser.find_by_id(self.id)
    if ((self.password != user.password) && (self.email != user.email))
      errors.add(:base, "Password is incorrect.")
    else
      self.password = user.password
    end
  end
end

app/controllers/js_users_controller.rb
class JsUsersController < ApplicationController
  before_action :set_user_params, only: [:show, :edit, :update, :destroy]

  def index
    @js_users = JsUser.all
  end

  def new
    @js_user = JsUser.new
  end

  def create
    @js_user = JsUser.create(user_params)
    if @js_user.save
      flash[:errors] = "User Created Sucesssfully"
      redirect_to js_users_path
    else
      flash[:errors] = @js_user.errors.full_messages
      redirect_to new_js_user_path
    end
  end

  def edit
  end

  def show
  end

  def update
    if @js_user.update(user_params)
      flash[:errors] = "User Updated Successfully"
      redirect_to js_user_path(@js_user)
    else
      flash[:errors] = @js_user.errors.full_messages
      redirect_to edit_js_user_path
    end
  end

  def destroy
    if @js_user.delete
      flash[:errors] = "User Deleted Successfully"
      redirect_to root_path
    else
      flash[:errors] = @js_user.errors.full_messages
      redirect_to destroy_js_user_path
    end
  end

  def profile
    @js_user = JsUser.find(params[:id])
  end

  def profile_update
    @js_user = JsUser.find(params[:id])
    respond_to do |format|
      if @js_user.update(user_params)
        flash[:notice] = "User Updated Successfully"
      else
        flash[:errors] = @js_user.errors.full_messages
      end
      format.js
    end
  end

  def changepassword
    @pwd = JsUser.find(params[:id])
  end

  def changepassword_update
    @user = JsUser.find(params[:id])
    if @user.update_attribute(:password, params[:new_password])
      flash[:notice] = "Password updated successfully"
      redirect_to js_user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to changepassword_js_user_path(@user)
    end
  end

  private

  def set_user_params
    @js_user = JsUser.find(params[:id])
  end

  def user_params
    params.require(:js_user).permit(:first_name, :last_name, :email, :password, :subscription, :subscription_email)
  end
end

app/helpers/js_users_helper.rb
module JsUsersHelper
end

app/views/js_users/_form.html.erb
<div class="center flex-column" id="vantajsnet">
  <div class="card shadow" style="width: 36rem;">
    <div class="card-header">
      <h2 class="text-center">User Form</h2>
    </div>
    <div class="card-body">
      <!--Error Message-->
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <p class="text-danger"><%= error %></p>
        <% end %>
      <% end %>
      <!-- Form Started Here -->
      <%= form_with model: @js_user do |f| %>
        <%= f.label :first_name, "First Name :", class:"mt-3" %>
        <%= f.text_field :first_name ,placeholder: "Enter Your First Name",class:"mb-2 form-control" %>
        <br>
        <%= f.label :last_name, "Last Name :" %>
        <%= f.text_field :last_name ,placeholder: "Enter Your Last Name",class:"mb-2 form-control" %>
        <br>
        <%= f.label :email, "E-mail ID :" %>
        <%= f.email_field :email ,placeholder: "Enter Your E-mail ID",class:"mb-2 form-control" %>
        <br>
        <%= f.label :password, "Password :" %>
        <%= f.password_field :password ,placeholder: "Enter Your Password",class:"mb-2 form-control" %>
        <br>
        <%= f.label :subscription, "Do you wanna Subscription?" %> &nbsp;
        <%= f.check_box :subscription,class:"form-check-input" %>
        <br>
        <%= f.label :subscription_email, "Subscription Email :", class:"mt-3" %>
        <%= f.email_field :subscription_email ,placeholder: "Enter Your E-mail",class:"mb-2 form-control" %>
        <br>
        <%= f.submit "Save User", class:"btn-primary border-0 rounded-pill shadow p-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/js_users/_userdetails.html.erb
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li style="color:red;"><%= error %></li>
    <% end %>
  </ul>
<% end %>
      <li style="color:green;"><%= notice %></li>
<div class="d-flex">
  <div class="card border-warning shadow" >
    <div class="card-body">
      <div class="card-header">
        <h3 class="text-center">User Details</h3>
      </div>
      <p> &#10145; First Name : <%= @js_user.first_name %> </p>
      <p> &#10145; Last Name : <%= @js_user.last_name %> </p>
      <p> &#10145; Password : <%= @js_user.password %> </p>
      <p> &#10145; Email : <%= @js_user.email %> </p>
      <p> &#10145; Subscription Mail : <%= @js_user.subscription_email %> </p>
    </div>
  </div>
</div>

app/views/js_users/changepassword.html.erb
<div class="center flex-column" id="vantajsnet">
  <div class="card shadow" style="width: 36rem;">
    <div class="card-header">
      <h2 class="text-center"> Change Password</h2>
    </div>
    <div class="card-body">
      <!--Error Message-->
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <p class="text-danger"><%= error %></p>
        <% end %>
      <% end %>
      <!-- Form Started Here -->
      <%= form_with model: @js_user, method: :patch, url: changepassword_update_js_user_path do |f| %>
        <div id="password_div" >
          <%= f.label :password, "Old Password :" %>
          <%= f.password_field :password ,placeholder: "Enter Your Password", class:"mb-2 form-control", oninput:"check_old_pwd();", id:"old_password" %>
        </div>
        <br>
        <div id="obj" style="display:none;">
          <%= f.label :new_password, "New Password :" %>
          <%= f.password_field :new_password ,placeholder: "Enter New Password", class:"mb-2 form-control", id:"new_password", oninput:"check_password();" %>
          <p id = "pwd_msg" style="color:red"> </p>
          <br>
          <%= f.label :password_confirmation, "Confirm Password :" %>
          <%= f.password_field :password_confirmation ,placeholder: "Confirm New Password", class:"mb-2 form-control", id:"password_confirmation", onchange:"check_password();" %>
          <p id = "pwd_match_msg" style="color:red"> </p>
          <br>
          <%= f.submit "Change", data: { disable_with: "Saving..." }, class:"btn-primary border-0 rounded-pill shadow p-3" %>
        </div>
      <% end %>
      <%= button_to "Back to Home", js_users_path, method: :get ,class:"btn-warning border-0 rounded-pill shadow p-3 my-3" %>
    </div>
  </div>
</div>
<!-- JAVASCRIPT -->
<script type="text/javascript">
  function check_old_pwd(){
      var pre_pwd = "<%=@pwd.password %>"
      if(document.getElementById("old_password").value == pre_pwd)
      {
        document.getElementById("pwd_match_msg").innerHTML="";
        document.getElementById("obj").style.display = "block";
      }else
      {
        document.getElementById("pwd_match_msg").innerHTML="Old Password is incorrect!";
        document.getElementById("obj").style.display = "none";
      }
    }
    function check_password() {
    var submit_btn = document.getElementById("submit");
    var new_pwd = document.getElementById('new_password').value
    var confirm_pwd = document.getElementById('password_confirmation').value
    var regularExpression  = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
    if(!regularExpression.test(new_pwd)) {
      document.getElementById("pwd_msg").innerHTML=
      "Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character";
    }else{
       document.getElementById("pwd_msg").innerHTML=""
    }
    if (new_pwd == confirm_pwd) {
       submit_btn.style.display= 'block';
        document.getElementById("pwd_match_msg").innerHTML="";
    } else {
        submit_btn.style.display= 'none';
        document.getElementById("pwd_match_msg").innerHTML="Password and confirm Password must be same!";
    }
  }
</script>

app/views/js_users/edit.html.erb
<%= render 'form' %>

app/views/js_users/index.html.erb
<div class="center flex-column">
  <h1> Users </h1>
  <!--Error Message-->
  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message %></p>
    <% end %>
  <% end %>
  <p class="text-success"><%= notice %></p>
  <!-- User Table -->
  <div>
    <table class="table table-info table-striped">
      <ol class="fs-2">
        <thead class="table-secondary">
          <td class="text-center"> Name </td>
          <td class="text-center"> Email </td>
          <td colspan=3 class="text-center"> Action </td>
        </thead>
        <% @js_users.each do |user| %>
          <tr>
            <td class="text-center"> <%= link_to user.first_name + " " + user.last_name, js_user_path(user) %> </td>
            <td class="text-center"> <%= user.email %> </td>
            <td class="text-center"><%= button_to "Show",js_user_path(user),method: :get, class:"btn-success border-0 rounded-pill shadow px-3 py-2" %></td>
            <td class="text-center"><%= button_to "Profile",profile_js_user_path(user),method: :get, class:"btn-primary border-0 rounded-pill shadow px-3 py-2" %></td>
            <td class="text-center"><%= link_to "Delete",js_user_path(user),data: {turbo_method: :delete, turbo_confirm: "Are you want delete?"}, class:"btn-danger border-0 rounded-pill shadow px-3 py-2" %></td>
          </tr>
        <% end %>
      </ol>
    </table>
  </div>
  <div class="d-flex">
    <%= button_to "Add New User", new_js_user_path, method: :get ,class:"btn-warning border-0 rounded-pill shadow p-3 m-3" %>
  </div>

app/views/js_users/new.html.erb
<%= render 'form' %>

app/views/js_users/profile.html.erb
<div class="center flex-column" id="vantajsnet">
  <div class="d-flex">
    <div class="card shadow" style="width: 36rem;">
      <div class="card-header">
        <h2 class="text-center">User Form</h2>
      </div>
      <div class="card-body">
        <!--Error Message-->
        <% if flash[:errors] %>
          <% flash[:errors].each do |error| %>
            <p class="text-danger"><%= error %></p>
          <% end %>
        <% end %>
        <!-- Form Started Here -->
        <%= form_with model: @js_user, method: :patch, url: profile_update_js_user_path, local: false do |f| %>
          <%= f.label :first_name, "First Name :", class:"mt-3" %>
          <%= f.text_field :first_name ,placeholder: "Enter Your First Name", class:"mb-2 form-control" %>
          <br>
          <%= f.label :last_name, "Last Name :" %>
          <%= f.text_field :last_name ,placeholder: "Enter Your Last Name", class:"mb-2 form-control" %>
          <br>
          <%= f.label :email, "E-mail ID :" %>
          <%= f.email_field :email ,placeholder: "Enter Your E-mail ID", class:"mb-2 form-control", id:"email", oninput: "ShowPasswordDiv()" %>
          <!-- Password Div -->
          <div id="password_div" style="display:none">
            <br>
            <%= f.label :password, "Password :" %>
            <%= f.password_field :password ,placeholder: "Enter Your Password", class:"mb-2 form-control", id: "old_pwd" %>
          </div>
          <br>
          <%= f.label :subscription, "Do you wanna Subscription?" %> &nbsp;
          <%= f.check_box :subscription, class:"form-check-input", onclick:"ShowHideSubEmailDiv(this)" %>
          <br>
          <!-- Subscription email Div -->
          <div id="sub_email_div" style="display: block">
            <%= f.label :subscription_email, "Subscription Email :", class:"mt-3" %>
            <%= f.email_field :subscription_email ,placeholder: "Enter Your E-mail", class:"mb-2 form-control" %>
          </div>
          <br>
          <%= f.submit "Update User", data: { disable_with: "Saving..." }, class:"btn-primary border-0 rounded-pill shadow p-3" %>
        <% end %>
        <%= button_to "Change Password", changepassword_js_user_path, method: :get ,class:"btn-warning border-0 rounded-pill shadow p-3 my-3" %>
      </div>
    </div>
    <!-- User Details that are fetch using AJAX Call -->
    <div id="userdetails" class="ms-3">
    </div>
  </div>
</div>
<!-- JAVASCRIPT -->
<script type="text/javascript">
  function ShowHideSubEmailDiv(subcription_check) {
    var sub_email_div = document.getElementById("sub_email_div");
    sub_email_div.style.display = !subcription_check.checked ? "none" : "block";
  }

  function ShowPasswordDiv() {
    var email_value = document.getElementById("email").value;
    // taking old email from js_user instance in controller
    var pre_email = "<%=@js_user.email %>";
    if (email_value != pre_email) {
      document.getElementById("password_div").style.display = "block";
    } else {
      document.getElementById("password_div").style.display = "none";
    }
  }
</script>

app/views/js_users/profile_update.js.erb
$("#userdetails").html('<%= escape_javascript(render('userdetails', js_user: @js_user)).html_safe %>');

app/views/js_users/show.html.erb
<!-- Event Details Showing -->
<div class="center flex-column" id="vantajs" style="height:100vh;">
  <!--Error Message-->
  <% if flash[:errors] %>
    <% flash.each do |name, message| %>
      <p class="text-danger"><%= message %></p>
    <% end %>
  <% end %>
  <p class="text-success"><%= notice %></p>
  <div class="d-flex">
    <div class="card border-warning shadow" >
      <div class="card-body">
        <div class="card-header">
          <h2 class="text-center">User Details</h2>
        </div>
        <h2> &#10145; First Name : <%= @js_user.first_name %> </h2>
        <h2> &#10145; Last Name : <%= @js_user.last_name %> </h2>
        <h2> &#10145; Password : <%= @js_user.password %> </h2>
        <h2> &#10145; Email : <%= @js_user.email %> </h2>
        <h2> &#10145; Subscription Mail : <%= @js_user.subscription_email %> </h2>
      </div>
      <div class="d-flex">
        <%= button_to "Edit User" , profile_js_user_path, method: :get ,class:"btn-success border-0 rounded-pill shadow p-2 m-2" %>
        <%= button_to "Delete User", js_user_path, method: :delete ,class:"btn-danger border-0 rounded-pill shadow p-2 m-2" %>
        <%= button_to "View all User", js_users_path,method: :get ,class:"btn-primary border-0 rounded-pill shadow p-2 m-2" %>
      </div>
    </div>
  </div>
</div>