config/routes.rb
Rails.application.routes.draw do
  get "user2s/index"
  get "user2s/edit"
  get "user2s/new"
  get "user2s/show"
  get "employee1s/index"
  get "employee1s/edit"
  get "employee1s/new"
  get "employee1s/show"
  devise_for :user1s
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # for Products
  resources :products
  # root 'products#index'

  # for Authors
  resources :authors
  # root 'authors#index'

  #for Books
  resources :books

  #for Faculties
  resources :faculties
  # root "faculties#index"

  #for Students
  resources :students

  # JavaScript with rails
  resources :js_users do
    member do
      get :profile
      patch :profile_update
      get :changepassword
      patch :changepassword_update
    end
  end

  root "js_users#index"

  #for Employees
  # root "employees#index"
  post "/increaseOrder", to: "employees#increaseOrder"
  post "/decreaseOrder", to: "employees#decreaseOrder"
  get "employees/task"
  resources :employees

  # root "myproducts#index"
  get "myproducts/defaultScope"
  get "orders/root"
  resources :myproducts
  resources :customers
  resources :orders

  # Active Record Association
  # root "events#index"
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: "log_in"
  delete "logout", to: "sessions#destroy"

  resources :users do
    collection do
      get :userprofile
    end
    member do
      get :enroll_event
      post :post_user
      get :unenroll_event
    end
  end

  resources :categories

  # Event Routes
  get "/:event_id/comments/new", to: "comments#new", :as => :new_comment
  post "/:event_id/comments/new", to: "comments#create"
  get "/events/:event_id/comments/:comment_id/edit", to: "comments#edit", :as => :edit_comment
  post "/events/:event_id/comments/:comment_id/edit/", to: "comments#update"
  delete "/events/:event_id/comments/:comment_id/", to: "comments#destroy", :as => :destroy_comment

  resources :events do
    resources :comments do
      member do
        post :like
      end
    end
  end

  # Resourceful Routes for rproducts
  resources :rproducts do
    resources :rorders
  end

  # Namespace Routing
  namespace :business do
    get "search", to: "rcustomers#search_customer"
    resources :rcustomers, only: [:index, :new, :create, :edit, :update] do
      member do
        get "name_preview"
        delete "delete_customer"
      end
    end
  end

  # root "rproducts#index"

  # Layouts Rendering Practical
  resources :user1s
  resources :product1s do
    resources :order1s
  end

  # root "home1s#index"

  # Action View form helpers
  get "search", to: "employee1s#search"
  resources :employee1s

  # root "employee1s#index"

  # Action mailer and basic file upload
  resources :user2s
  #root "user2s#index"

  # Test Cases Practical
  resources :product2s
  # root "home1s#index"

end

app/models/rcustomer.rb
class Rcustomer < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :phone_number, presence: true, numericality: { only_integer: true }
end

app/controllers/business/rcustomers_controller.rb
class Business::RcustomersController < ApplicationController
  def index
    @rcustomers = Rcustomer.all
  end

  def new
    @rcustomer = Rcustomer.new
  end

  def create
    @rcustomer = Rcustomer.create(rcustomer_params)
    if @rcustomer.valid?
      flash[:errors] = "Customer Created Successfully"
      redirect_to business_rcustomers_path
    else
      flash[:errors] = @rcustomer.errors.full_messages
      redirect_to new_business_rcustomer_path
    end
  end

  def edit
    @rcustomer = Rcustomer.find(params[:id])
  end

  def update
    @rcustomer = Rcustomer.find(params[:id])
    if @rcustomer.update(rcustomer_params)
      flash[:errors] = "Customer Updated Successfully"
      redirect_to name_preview_business_rcustomer_path(@rcustomer)
    else
      flash[:errors] = @rcustomer.errors.full_messages
      redirect_to edit_business_rcustomer_path
    end
  end

  def name_preview
    @rcustomer = Rcustomer.find(params[:id])
  end

  def delete_customer
    @rcustomer = Rcustomer.find(params[:id])
    if @rcustomer.delete
      flash[:errors] = "Customer Deleted Successfully"
      redirect_to business_rcustomers_path
    else
      flash[:errors] = @rcustomer.errors.full_messages
      redirect_to destroy_business_rcustomer_path
    end
  end

  def search_customer
    if params[:searchParams].blank?
      flash[:errors] = "Enter Valid Data!!"
      redirect_to business_rcustomers_path
    else
      parameter = params[:searchParams].downcase
      @rcustomers = Rcustomer.where("lower(name) LIKE ? ", parameter)
      flash[:errors] = "Customer Searched Successfully"
    end
  end

  private

  def rcustomer_params
    params.require(:rcustomer).permit(:name, :email, :phone_number)
  end
end

app/helpers/rcustomers_helper.rb
module RcustomersHelper
end

app/views/business/rcustomers/_form.html.erb
<div class="center flex-column" id="vantajs" style="height:100vh;">
  <div class="card bg-light border-warning shadow" style="width: 22rem;">
    <div class="card-body">
      <div class="card-header">
        <h2 class="text-center">Customer Form</h2>
      </div>
      <!--Error Message-->
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <p class="text-danger"><%= error %></p>
        <% end %>
      <% end %>
      <!-- Form Started Here -->
      <%= form_with(model: [:business, @rcustomer]) do |rcustomer| %>
        <%= rcustomer.label :name, "First Name :", class:"mt-3" %>
        <%= rcustomer.text_field :name ,placeholder: "Enter Customer's Name",class:"mb-2 form-control" %>
        <br>
        <%= rcustomer.label :email, "Email :" %>
        <%= rcustomer.text_field :email ,placeholder: "Enter Customer's email",class:"mb-2 form-control" %>
        <br>
        <%= rcustomer.label :phone_number, "Phone Number :" %>
        <%= rcustomer.telephone_field :phone_number ,placeholder: "Enter Customer's phone_number",class:"mb-2 form-control" %>
        <br>
        <%= rcustomer.submit class:"btn-primary border-0 rounded-pill shadow p-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/business/rcustomers/edit.html.erb
<!-- Customer form -->
<%= render 'form' %>

app/views/business/rcustomers/index.html.erb
<%= render 'layouts/navbar'%>
<div class="center flex-column" id="vantajs" style="height:100vh;">
  <h1> Customers </h1>
  <!--Error Message-->
  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>
  <!-- Search bar for Searching Customer -->
  <div class="mb-3">
    <%= form_tag business_search_path, :method => "get" do %>
      <div class="d-flex">
        <%= text_field_tag :searchParams, params[:searchParams], placeholder: "Search Customer", class: "form-control me-2" %>
        <%= submit_tag "Search", class: "btn btn-success me-2" %>
      </div>
    <% end %>
  </div>
  <!-- Customer Table -->
  <div>
    <table class="table table-info table-striped">
      <ol class="fs-2">
        <thead class="table-secondary">
          <td class="text-center"> Name </td>
          <td class="text-center"> Email </td>
          <td class="text-center"> Phone  </td>
          <td colspan=3 class="text-center"> Action </td>
        </thead>
        <% @rcustomers.each do |rcustomer| %>
          <tr>
            <td class="text-center"> <%= rcustomer.name %> </td>
            <td class="text-center"> <%= rcustomer.email %> </td>
            <td class="text-center"> <%= rcustomer.phone_number %> </td>
            <td class="text-center"><%= button_to "Show",name_preview_business_rcustomer_path(rcustomer),method: :get, class:"btn-success border-0 rounded-pill shadow px-3 py-2" %></td>
            <td class="text-center"><%= button_to "Edit",edit_business_rcustomer_path(rcustomer),method: :get, class:"btn-primary border-0 rounded-pill shadow px-3 py-2" %></td>
            <td class="text-center"><%= button_to "Delete",delete_customer_business_rcustomer_path(rcustomer),method: :delete, class:"btn-danger border-0 rounded-pill shadow px-3 py-2" %></td>
          </tr>
        <% end %>
      </ol>
    </table>
  </div>
  <div class="d-flex">
    <%= button_to fa_icon("plus", text: "Add New Customer"), new_business_rcustomer_path, method: :get ,class:"btn-warning border-0 rounded-pill shadow p-3 m-3" %>
    <%= button_to fa_icon("cube", text: "Product Page"), rproducts_path, method: :get ,class:"btn-warning border-0 rounded-pill shadow p-3 m-3" %>
  </div>
</div>

app/views/business/rcustomers/name_preview.html.erb
<!-- Customer Details Showing -->
<div class="center flex-column" id="vantajs" style="height:100vh;">
  <!--Error Message-->
  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>
  <div>
    <div class="card bg-light border-warning shadow">
      <div class="card-body">
        <div class="card-header">
          <h2 class="text-center">Customer Details</h2>
        </div>
        <div>
          <h2> &#10145; ID: <%= @rcustomer.id %> </h2>
          <h2> &#10145; Name: <%= @rcustomer.name %> </h2>
          <h2> &#10145; Email: <%= @rcustomer.email %> </h2>
          <h2> &#10145; Phone Number: <%= @rcustomer.phone_number %> </h2>
        </div>
        <div class="d-flex">
          <%= button_to "Edit Customer" , edit_business_rcustomer_path, method: :get ,class:"btn-success border-0 rounded-pill shadow p-2 m-2" %>
          <%= button_to "Delete Customer", delete_customer_business_rcustomer_path(@rcustomer), method: :delete ,class:"btn-danger border-0 rounded-pill shadow p-2 m-2" %>
          <%= button_to "View all Customers", business_rcustomers_path, method: :get ,class:"btn-primary border-0 rounded-pill shadow p-2 m-2" %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/business/rcustomers/new.html.erb
<!-- Customer form -->
<%= render 'form' %>

app/views/business/rcustomers/search_customer.html.erb
<div class="center flex-column" id="vantajs" style="height:100vh;">
  <div class="card bg-light border-warning shadow" >
    <div class="card-body">
      <div class="card-header">
        <h2 class="text-center">Search Result</h2>
      </div>
      <!--Error Message-->
      <% if flash[:errors] %>
        <% flash.each do |name,message| %>
          <p class="text-danger"><%= message%></p>
        <% end %>
      <% end %>
      <% @rcustomers.each do |rcustomer|%>
        <div>
          <h2> &#10145; Name: <%= rcustomer.name %> </h2>
          <h2> &#10145; Email: <%= rcustomer.email %> </h2>
          <h2> &#10145; Phone Number: <%= rcustomer.phone_number %> </h2>
        </div>
        <div class="d-flex">
          <%= button_to "Edit Customer" , edit_business_rcustomer_path(rcustomer), method: :get ,class:"btn-success border-0 rounded-pill shadow p-2 m-2" %>
          <%= button_to "Delete Customer", delete_customer_business_rcustomer_path(rcustomer), method: :delete ,class:"btn-danger border-0 rounded-pill shadow p-2 m-2" %>
          <%= button_to "View all Customers", business_rcustomers_path, method: :get ,class:"btn-primary border-0 rounded-pill shadow p-2 m-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>