config/routes.rb
Rails.application.routes.draw do
  get "user2s/index"
  get "user2s/edit"
  get "user2s/new"
  get "user2s/show"
  get "employee1s/index"
  get "employee1s/edit"
  get "employee1s/new"
  get "employee1s/show"
  devise_for :user1s
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # for Products
  resources :products
  # root 'products#index'

  # for Authors
  resources :authors
  # root 'authors#index'

  #for Books
  resources :books

  #for Faculties
  resources :faculties
  # root "faculties#index"

  #for Students
  resources :students

  # JavaScript with rails
  resources :js_users do
    member do
      get :profile
      patch :profile_update
      get :changepassword
      patch :changepassword_update
    end
  end

  root "js_users#index"

  #for Employees
  # root "employees#index"
  post "/increaseOrder", to: "employees#increaseOrder"
  post "/decreaseOrder", to: "employees#decreaseOrder"
  get "employees/task"
  resources :employees

  # root "myproducts#index"
  get "myproducts/defaultScope"
  get "orders/root"
  resources :myproducts
  resources :customers
  resources :orders

  # Active Record Association
  # root "events#index"
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: "log_in"
  delete "logout", to: "sessions#destroy"

  resources :users do
    collection do
      get :userprofile
    end
    member do
      get :enroll_event
      post :post_user
      get :unenroll_event
    end
  end

  resources :categories

  # Event Routes
  get "/:event_id/comments/new", to: "comments#new", :as => :new_comment
  post "/:event_id/comments/new", to: "comments#create"
  get "/events/:event_id/comments/:comment_id/edit", to: "comments#edit", :as => :edit_comment
  post "/events/:event_id/comments/:comment_id/edit/", to: "comments#update"
  delete "/events/:event_id/comments/:comment_id/", to: "comments#destroy", :as => :destroy_comment

  resources :events do
    resources :comments do
      member do
        post :like
      end
    end
  end

  # Resourceful Routes for rproducts
  resources :rproducts do
    resources :rorders
  end

  # Namespace Routing
  namespace :business do
    get "search", to: "rcustomers#search_customer"
    resources :rcustomers, only: [:index, :new, :create, :edit, :update] do
      member do
        get "name_preview"
        delete "delete_customer"
      end
    end
  end

  # root "rproducts#index"

  # Layouts Rendering Practical
  resources :user1s
  resources :product1s do
    resources :order1s
  end

  # root "home1s#index"

  # Action View form helpers
  get "search", to: "employee1s#search"
  resources :employee1s

  # root "employee1s#index"

  # Action mailer and basic file upload
  resources :user2s
  #root "user2s#index"

  # Test Cases Practical
  resources :product2s
  # root "home1s#index"

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
  belongs_to :user
  validates :category_name, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category= Category.create(category_params)
    if @category.valid?
      flash[:notice] = "Category Added!"
      redirect_to categories_path
    else
      flash[:errors] = @category.errors.full_messages
      redirect_to new_category_path
    end
  end

  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:errors] = "Category Update Successfully"
      redirect_to category_path(@category)
    else
      flash[:errors] = @category.errors.full_messages
      redirect_to edit_category_path
    end
  end
  
  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.delete
      flash[:errors] = "Category Deleted Successfully"
      redirect_to categories_path
    else
      flash[:errors] = @category.errors.full_messages
      redirect_to destroy_category_path
    end
  end

  private
  def category_params
    params.require(:category).permit(:category_name, :user_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<!-- For for New or Edit -->
<div class="center flex-column border-warning shadow" id="vantajs" style="height:100vh;">
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <p class="text-danger"><%= error %></p>
    <% end %>
  <% end %>
  <!-- Form Started Here -->
  <div class="card bg-light border-warning shadow" style="width: 22rem;">
    <div class="card-body">
      <div class="card-header">
        <h2 class="text-center">Category Form</h2>
      </div>
      <p class="card-text">Different Categories like Art, Music, Food, Dance, Visual etc</p>
      <% if @current_user %>
        <%= form_for @category do |category| %>
          <%= category.label :category_name, "Category Name :", class: "mt-3" %>
          <%= category.text_field :category_name, placeholder: "Enter Event's Name", class: "mb-2 form-control" %>
          <br>
          <div>
            <%= category.number_field :user_id, value: @current_user.id, type: :hidden %>
          </div>
          <%= category.submit class: "btn-primary border-0 rounded-pill shadow p-3" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<!-- Edit your Category -->
<%= render "form" %>

app/views/categories/index.html.erb
<div class="center flex-column" id="vantajs" style="height:100vh;">
  <h1> Categories </h1>
  <% if flash[:errors] %>
    <% flash.each do |name, message| %>
      <div class="alert alert-success" role="alert">
        <%= message %>
      </div>
    <% end %>
  <% end %>
  <!-- category Table Display when user logged in -->
  <% if @current_user %>
    <div class="d-flex">
      <%= link_to "Logout", logout_path, data: { 'turbo-method': :delete }, class: "btn-danger border-0 rounded-pill shadow px-3 py-2 me-2 text-decoration-none" %>
    </div>
    <div>
      <table class="table table-info table-striped">
        <ol class="fs-2">
          <thead class="table-secondary">
            <td class="text-center"> Id </td>
            <td class="text-center"> Category Name </td>
            <td colspan=3 class="text-center"> Action </td>
          </thead>
          <% @categories.each do |category| %>
            <tr>
              <td class="text-center"> <%= category.id %> </td>
              <td class="text-center"> <%= link_to category.category_name, category_path(category) %> </td>
              <td class="text-center">
                <% if @current_user.id == category.user_id %>
                  <%= button_to "Edit", edit_category_path(category), method: :get, class: "btn-success border-0 rounded-pill shadow px-3 py-2" %>
                <% end %>
              </td>
              <td class="text-center">
                <% if @current_user.id == category.user_id %>
                  <%= button_to "Delete", category_path(category), method: :delete, class: "btn-danger border-0 rounded-pill shadow px-3 py-2" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </ol>
      </table>
    </div>
    <div class="d-flex">
      <%= button_to fa_icon("plus", text: "Add New category"), new_category_path, method: :get, class: "btn-warning border-0 rounded-pill shadow p-3 m-3" %>
      <%= button_to fa_icon("user-circle", text: "My Profile"), userprofile_users_path, method: :get, class: "btn-success border-0 rounded-pill shadow p-3 m-3" %>
      <%= button_to fa_icon("user-circle", text: "View Events"), events_path, method: :get, class: "btn-success border-0 rounded-pill shadow p-3 m-3" %>
    </div>
  <% end %>
</div>
</div>

app/views/categories/new.html.erb
<!-- Add New Category Form -->
<%= render "form" %>